//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEventRegistration
    {
        public int RegId { get; set; }
        public int EventId { get; set; }
        public int UserId { get; set; }
        public int IsDonated { get; set; }
    
        public virtual tbEvent tbEvent { get; set; }
        public virtual tbUser tbUser { get; set; }
    }
}
